name: CloudFlare Worker Publish

on:
  push:
    branches:
      - worker

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Install dependencies
        run: npm install
  deploy:
    runs-on: ubuntu-latest
    name: Deploy
    needs: build
    steps:
      - uses: actions/checkout@v3
      - name: Publish app
        uses: cloudflare/wrangler-action@2.0.0
        with:
          apiToken: ${{ secrets.CF_API_TOKEN }}
          accountId: ${{ secrets.CF_ACCOUNT_ID }}
        env:
          MONGODB_DATAAPI_APPID: ${{ secrets.MONGODB_DATAAPI_APPID }}
          MONGODB_DATAAPI_APIKEY: ${{ secrets.MONGODB_DATAAPI_APIKEY }}
          PROXY_URL: ${{ secrets.PROXY_URL }}
